== Reference Object와 Value Object

OOP의 관점에서 데이터를 어떻게 다루는지를 알아봅니다.

=== Reference Object와 Value Object를 구분하기

"홍길동"이라는 고객이 있고 이를 객체로 표현하였다. 고객이 한달전에 주문한 정보나 환불내역과 같은 정보는 홍길동이라는 객체가 가지게 될 것이다. 즉 지금 시점에서 "홍길동"이라는 사람의 정보를 조회할 경우 앞선 정보들까지 모두 가져올 수 있어야 한다. "홍길동" 고객 객체가 여러개 존재한다면 프로그램에서는 큰 혼란이 일어날것이다. 그렇기 때문이 이 "고객" 객체는 프로그램에서 단 하나만 존재하여야지만 위와같은 문제를 방지할 수 있을 것이다. 이를 우리는 Reference Object라고 정의하도록 하자.

"주소"라는 객체가 있으며 이 객체는 "주문"이라는 맥락내에서 사용한다고 해보자. 이 "주소"는 위와 같이 변화를 추적하며 정보를 확인해야 할 필요성이 없다. 단순히 내부의 값만을 사용하기 때문이며, "주문"객체와 동일한 생명주기를 가지기 때문이다.  전화번호나 주문날짜도 이와 같은 맥락에 속하는 속성을 가진다. 이처럼 추적이 굳이 필요없는 객체들의 경우 Value Object라는 개념으로 묶어서 관리하게 된다.

=== 동일함의 의미

위의 Reference Object는 동일함을 `==`를 사용하여 표현해 줄 수 있을 것이다. 일반적으로 자바에서는 객체가 생성될 때 메모리주소를 사용해 동일함을 비교하게 된다. 반면 주소와 같은 Value Object는 값에만 관심이 있다. 내부의 값이 같을 경우에는 동일한 객체라고 판별할 수 있을 것이다. 따라서 ValueObject는 equals 메서드를 활용하여 두 객체가 동일한지를 판단한다.

=== 별칭문제

=== Value Object는 불변의 속성을 가져야 한다.

* setter 없애기

==== Reference Object 관리하기

* 시스템은 어떤 객체를 수정하거나 조작한다.
* 외부와 접점이 되는 부분을 Entry Point라고 칭한다.
* 이 Entry Point로 앞서 만든 Reference Object를 사용하도록 하자
* Reference Object는 메모리를 통해서 저장되게 된다.
* 생성된 Reference Object를 통합적으로 관리할 수 있도록 `Registar`를 만들어 보자

==== Registar를 분리하기

* 객체의 비즈니스적인 역할과
* 저장하는 행위를 분리시킨다.



